### ISSUE TITLE
SyntaxError: Unexpected token = on Ubuntu 17.04

### ISSUE THREAD

**Issue by Akronix** [tldr-pages/tldr#1734]
I installed tldr using `sudo npm install -g tldr `, but when I try to use it for any argument I get this error:
```

/usr/local/lib/node_modules/tldr/lib/tldr.js:130
function printBestPage(command, options={}) {
                                       ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/tldr/bin/tldr:5:14)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
```

I'm on Ubuntu 17.04 and my npm version is 3.5.2.

**Comment by agnivade** [comment]
Our minimum required node version is 6. You must have got a warning when installing the package. Please upgrade to the latest LTS version.

I will close this issue now. But if you still have problems, please raise a separate issue in the tldr-node-client repo with details about your environment and proper repro steps. This repo is only for the tldr pages not clients.

**Comment by Akronix** [comment]
Yep, indeed there was a warning.
I've upgraded both npm and node and now it's working. Thanks.
