### ISSUE TITLE
Issue when installing in Ubuntu 17.10

### ISSUE THREAD

**Issue by axelitus** [tldr-pages/tldr#1748]
When I try installing tldr globally in Ubuntu 17.10 as root I get the following error:

```
gyp WARN EACCES user "root" does not have permission to access the dev dir "/usr/lib/node_modules/tldr/node_modules/webworker-threads/.node-gyp/8.7.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/lib/node_modules/tldr/node_modules/webworker-threads/.node-gyp"
```

I'm using
- Node: v8.7.0
- Npm: 5.5.1

![screenshot from 2017-12-04 13-43-44](https://user-images.githubusercontent.com/732441/33572702-4fce5f30-d8f9-11e7-8c46-ec667640ffd5.png)

The installation seems to get stuck in a loop trying to reinstall that module as the image shows. I need to stop the process with `Ctrl + C` but then trying to run the command I get the following error:

```
/usr/lib/node_modules/tldr/node_modules/natural/lib/natural/classifiers/classifier.js:32
    if (e.code !== 'MODULE_NOT_FOUND') throw e;
                                       ^

Error: Could not locate the bindings file. Tried:
 → /usr/lib/node_modules/tldr/node_modules/webworker-threads/build/WebWorkerThreads.node
 → /usr/lib/node_modules/tldr/node_modules/webworker-threads/build/Debug/WebWorkerThreads.node
 → /usr/lib/node_modules/tldr/node_modules/webworker-threads/build/Release/WebWorkerThreads.node
 → /usr/lib/node_modules/tldr/node_modules/webworker-threads/out/Debug/WebWorkerThreads.node
 → /usr/lib/node_modules/tldr/node_modules/webworker-threads/Debug/WebWorkerThreads.node
 → /usr/lib/node_modules/tldr/node_modules/webworker-threads/out/Release/WebWorkerThreads.node
 → /usr/lib/node_modules/tldr/node_modules/webworker-threads/Release/WebWorkerThreads.node
 → /usr/lib/node_modules/tldr/node_modules/webworker-threads/build/default/WebWorkerThreads.node
 → /usr/lib/node_modules/tldr/node_modules/webworker-threads/compiled/8.7.0/linux/x64/WebWorkerThreads.node
    at bindings (/usr/lib/node_modules/tldr/node_modules/bindings/bindings.js:93:9)
    at Object.<anonymous> (/usr/lib/node_modules/tldr/node_modules/webworker-threads/index.js:1:105)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/lib/node_modules/tldr/node_modules/natural/lib/natural/classifiers/classifier.js:29:19)
```

**Comment by agnivade** [comment]
Please have a look here - https://github.com/tldr-pages/tldr-node-client#installation-issues.

I will close the issue now as this repo is only for pages. If your problem still persists, please open an issue in the node client's repo with proper environment details and repro steps.
