### ISSUE TITLE
Update fails

### ISSUE THREAD

**Issue by zeke** [tldr-pages/tldr#263]
```
z* master » tldr grep
Page not found
Try updating with --update, or submit a pull request to 
http://github.com/tldr-pages/tldr

z* master » tldr --update
Updating...
Error: invalid signature: 0x6d6f632f
    at /Users/z/.nvm/v0.10.35/lib/node_modules/tldr/node_modules/unzip/lib/parse.js:59:13
    at processImmediate [as _immediateCallback] (timers.js:354:15)

z* master » npm -v
2.5.0

z* master » node -v
v0.10.35
```

**Comment by rprieto** [comment]
Thanks @zeke. This sounds like it could be a problem in https://github.com/tldr-pages/tldr-node-client.
Do you mind updating to the latest version (`npm install tldr -g`), and raising it over there if it's not fixed?

**Comment by rprieto** [comment]
Thanks @rubenvereecken for opening it on the Node client, let's close this one.
