### ISSUE TITLE
can't render

### ISSUE THREAD

**Issue by isomorphisms** [tldr-pages/tldr#264]
Rendering a local file fails like so on the `npm` version.

```
$ tldr --render test.md

/usr/local/lib/node_modules/tldr/lib/tldr.js:55
    console.log(output.fromMarkdown(fs.readFileSync(file) + ''));
                ^
ReferenceError: output is not defined
    at Object.exports.render (/usr/local/lib/node_modules/tldr/lib/tldr.js:55:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/tldr/bin/tldr:54:42)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:929:3
```

```
$ cat test.md
#hi

how are you

- how
- is
- your
- day
```

**Comment by rprieto** [comment]
Hi, do you know which version you're using?  (try `npm list -g --depth=0 | grep tldr`)

**Comment by igorshubovych** [comment]
@rprieto,

Let's close this issue. It is too old.

I tested slightly modified version of given test page and it works for me.
```Markdown
# hi

> how are you

- how

`how`

- is

`is`

- your

`is`

- day

`day`
```

If @isomorphisms reappears, we can always reopen it.

**Comment by igorshubovych** [comment]
I am closing it. Feel free to reopen if issue reoccurs.
