### ISSUE TITLE
permission denied on sudo npm install -g tldr

### ISSUE THREAD

**Issue by GabLeRoux** [tldr-pages/tldr#820]
Hello, I did a clean install on Arch Linux
```
sudo pacman -S nodejs npm
```

```
sudo npm install -g tldr
```

```
 Please update to graceful-fs@^4.0.0 as soon as possible.
/usr/bin/tldr -> /usr/lib/node_modules/tldr/bin/tldr

> tldr@1.6.0 postinstall /usr/lib/node_modules/tldr
> node ./bin/tldr --update

Updating...
/usr/lib/node_modules/tldr/node_modules/wrench/lib/wrench.js:481
            throw err;
            ^

Error: EACCES: permission denied, mkdir '/root/.tldr'
    at Error (native)
    at Object.fs.mkdirSync (fs.js:842:18)
    at mkdirSyncRecursive (/usr/lib/node_modules/tldr/node_modules/wrench/lib/wrench.js:466:12)
    at Object.mkdirSyncRecursive (/usr/lib/node_modules/tldr/node_modules/wrench/lib/wrench.js:473:17)
    at /usr/lib/node_modules/tldr/lib/cache.js:55:12
    at Extract.<anonymous> (/usr/lib/node_modules/tldr/lib/remote.js:28:5)
    at emitNone (events.js:85:20)
    at Extract.emit (events.js:179:7)
    at DirWriter.<anonymous> (/usr/lib/node_modules/tldr/node_modules/unzip2/lib/extract.js:42:10)
    at emitNone (events.js:85:20)
npm ERR! Linux 4.4.3-1-ARCH
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "-g" "tldr"
npm ERR! node v5.7.1
npm ERR! npm  v3.8.0
npm ERR! code ELIFECYCLE

npm ERR! tldr@1.6.0 postinstall: `node ./bin/tldr --update`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the tldr@1.6.0 postinstall script 'node ./bin/tldr --update'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the tldr package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/tldr --update
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs tldr
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls tldr
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/gableroux/npm-debug.log
```

from `npm-debug.log`

```
9943 verbose unlock done using /root/.npm/_locks/staging-a072192f34a17023.lock for /usr/lib/node_modules/.staging
9944 silly rollbackFailedOptional Starting
9945 silly rollbackFailedOptional Finishing
9946 silly runTopLevelLifecycles Starting
9947 silly runTopLevelLifecycles Finishing
9948 silly install printInstalled
9949 verbose stack Error: tldr@1.6.0 postinstall: `node ./bin/tldr --update`
9949 verbose stack Exit status 1
9949 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:239:16)
9949 verbose stack     at emitTwo (events.js:100:13)
9949 verbose stack     at EventEmitter.emit (events.js:185:7)
9949 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:24:14)
9949 verbose stack     at emitTwo (events.js:100:13)
9949 verbose stack     at ChildProcess.emit (events.js:185:7)
9949 verbose stack     at maybeClose (internal/child_process.js:827:16)
9949 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
9950 verbose pkgid tldr@1.6.0
9951 verbose cwd /home/gableroux
9952 error Linux 4.4.3-1-ARCH
9953 error argv "/usr/bin/node" "/usr/bin/npm" "install" "-g" "tldr"
9954 error node v5.7.1
9955 error npm  v3.8.0
9956 error code ELIFECYCLE
9957 error tldr@1.6.0 postinstall: `node ./bin/tldr --update`
9957 error Exit status 1
9958 error Failed at the tldr@1.6.0 postinstall script 'node ./bin/tldr --update'.
9958 error Make sure you have the latest version of node.js and npm installed.
9958 error If you do, this is most likely a problem with the tldr package,
9958 error not with npm itself.
9958 error Tell the author that this fails on your system:
9958 error     node ./bin/tldr --update
9958 error You can get information on how to open an issue for this project with:
9958 error     npm bugs tldr
9958 error Or if that isn't available, you can get their info via:
9958 error     npm owner ls tldr
9958 error There is likely additional logging output above.
9959 verbose exit [ 1, true ]
```

**Comment by GabLeRoux** [comment]
Quick and dirty solution is

**Comment by GabLeRoux** [comment]
Solution:
https://docs.npmjs.com/getting-started/fixing-npm-permissions

**Comment by rubenvereecken** [comment]
Yay
